# Generated by Django 5.2.6 on 2025-09-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('basketball', 'Basketball Shoes'), ('football', 'Football Shoes'), ('running', 'Running Shoes'), ('tennis', 'Tennis Shoes')], default='update', max_length=20),
        ),
    ]
