# Generated by Django 5.2.6 on 2025-09-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Football Shoes'), ('jersey', 'Jersey and Apparel'), ('equipment', 'Training Equipment'), ('merchandise', 'Club Merchandise')], default='update', max_length=20),
        ),
    ]
